spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled:true
      routes:
        - id: products-service
          uri: lb://pos-products
          predicates:
            - Path=/api/products/**
        - id: carts-service
          uri: lb://pos-carts
          predicates:
            - Path=/carts/**


server:
  port: 8080


